#ifndef IMPLEMENTATION_EXCLUDE_TEMPLATE
#define TEMPLATE_IMPLEMENTATION
#include "template.h"
#endif // !IMPLEMENTATION_EXCLUDE_TEMPLATE

#ifndef IMPLEMENTATION_EXCLUDE_PYTHON
#define PYTHON_IMPLEMENTATION
#include "python.h"
#endif // !IMPLEMENTATION_EXCLUDE_PYTHON

#ifndef IMPLEMENTATION_EXCLUDE_CMAKE
#define CMAKE_IMPLEMENTATION
#include "cmake.h"
#endif // !IMPLEMENTATION_EXCLUDE_CMAKE

#ifndef IMPLEMENTATION_EXCLUDE_MAKEFILE
#define MAKEFILE_IMPLEMENTATION
#include "makefile.h"
#endif // !IMPLEMENTATION_EXCLUDE_MAKEFILE
